const header = {
  // all the properties are optional - can be left empty or deleted
  homepage: 'http://localhost:3000/cleanfolio',
  title: 'JS.',
}

const about = {
  // all the properties are optional - can be left empty or deleted
  name: 'Parth Parekh',
  role: 'Software Developer',
  description:
    'Recently, I completed my masters in applied computer science from Concordia University. Prior to this, I was working as a Software Development Engineer at Yellow.ai and a Data Engineer at Fokal.ai. My areas of interest includes web applications, cloud technologies and distributed systems. I enjoy creating simple and effective solutions to improve application perfomance and building things that empowersothers to do the same.',
  social: {
    linkedin: 'https://www.linkedin.com/in/parth-parekh-bb9091174/',
    github: 'https://github.com/parth2347',
  },
}

const projects = [
  // projects can be added an removed
  // if there are no projects, Projects section won't show up
  {
    name: 'Video Streaming Application',
    description:
      'Built a DASH-compliant application that uploads the live video streamlets to a nodejs server reliably on the fly. The uploaded video is then played in the Dash JavaScript player.',
    stack: ['Javascript', 'Node.js', 'Dash', 'MySQL'],
    sourceCode: 'https://github.com/parth2347/Video-Streaming-Application'
  },
  {
    name: 'Load Balancer',
    description:
      'Developed a load balancer in Golang that redirects the request to the server having the least number of connections.',
    stack: ['Golang', 'Reverse Proxy'],
    sourceCode: 'https://github.com/parth2347/load-balancer',
  },
  {
    name: 'Restaurant Recommendation System',
    description:
      'Developed a restaurant recommendation system for the city of Montreal which provides personalized recommendations based on customer reviews and ratings for the restaurant.',
    stack: ['Pyspark', 'Python'],
    sourceCode: 'https://github.com/parth2347/Restaurant-Recommendation-System'
  },
  {
    name: 'E-Commerce App',
    description:
      'Developed an E-Commerce web application using nodejs as a backend and react as a frontend. The app was built using microservices architecture and also deployed to the cloud using docker.',
    stack: ['NodeJS', 'React', 'MongoDB'],
    sourceCode: 'https://github.com/parth2347/E-Commerce-App.git'
  },
  {
    name: 'Github Clone',
    description:
      'Developed a full stack web application using Java play framework which applies several programming concepts like streams, lambda and also made it a reactive server push app using Websockets and Akka actors.',
    stack: ['Java play framework', 'Junit'],
    sourceCode: 'https://github.com/parth2347/git-clone',
  },
]

const experiences = [
  {
    companyName: "Nakisa",
    role: "Software Developer Intern",
    fromDate: "May, 2022",
    toDate: "April, 2023",
    image: "./nakisa.png",
    description: ["• Maintaining an automation tool built using Spring Boot which creates confluence pages for showing project statistics.", 
                  "• Developed a log metric system to analyze critical and noncritical logs generated by the server.", 
                  "• Developed a crud web application with Spring Boot and MySQL as a database for storing and retrieving user profiles.",
                  "• Collaborated with the lead developer to refactor the old code base and optimize database queries, improving page responsiveness by 17%."],
    type: "Delivering robust high quality, robust production code for an automation tool that shows project statistics to clients",
    duration: "May 2022 - Present"
  },
  {
    companyName: "Yellow.ai",
    role: "Software Development Engineer",
    fromDate: "December, 2020",
    toDate: "August, 2021",
    image: "./nakisa.png",
    description: ["• Single-handedly implemented Node.js backend for a data explorer tool that uses Apache Druid as a database. This tool reduced 70% of the queries from customers about their data.", 
    "• Developed a Golang service with rate limiting functionality that ingests user events data from Kafka topic to database.", 
    "• Proposed and created a Golang service that checks the health and response time of servers and notifies us if any server is down which helped us achieve close to 100% of availability.",
    "• Developed a Node.js service that gets raw data from the MongoDB database and stores it into a blob which is then uploaded to Azure blob storage so that it can be retrieved by customers via a dedicated link."], 

    type: "Developed multiple microservices in Node.js and Golang which is being used by millions of customers",
    duration: "Dec 2020 - Aug 2021"
  },
  {
    companyName: "Fokal.ai",
    role: "Data Engineer",
    fromDate: "Januray, 2020",
    toDate: "December, 2020",
    image: "./nakisa.png",
    description: ["• Enhanced the functionality of CI/CD pipeline by including unit testing capability in the Jenkins which reduced 20% of development time as bugs were identified at the source only.", 
    "• Revitalized groovy script in Jenkins server for automatically creating an AWS layer based on python packages provided.", 
    "• Containerized legacy applications to automate the deployment process & improved scalability, resulting in 70% faster deployment cycles and 40% reduction in infrastructure costs.",
    "• Developed a slack app in Python for automatically providing AWS IAM permissions to project teams which reduced the workload on cloud engineers.", 
    "• Created serverless analytics of production failures with Tableau and AWS Athena."],
    type: "Developed multiple cloud related projects and also maintained CI/CD pipeline.",
    duration: "Jan 2020 - Dec 2020"
  }
]

const skills = [
  // skills can be added or removed
  // if there are no skills, Skills section won't show up
  'C/C++',
  'Java',
  'JavaScript',
  'Golang',
  'Python',
  'Node.js',
  'Spring Boot',
  'AWS',
  'Jenkins',
  'CI/CD',
  'Apache Kafka',
  'Apache Spark',
  'MySQL',
  'Docker'  
]

const contact = {
  // email is optional - if left empty Contact section won't show up
  email: 'parthparekh407@gmail.com',
}

export { header, about, projects, skills, contact, experiences }
